# Modular options
# true = enable module
# false = false module
module:
  auto-add-mob-to-config: true
  money: true
  exp: true

# Internal Placeholder
# {min} -> return based value min
# {max} -> return based value max
# PlaceholderAPi Support too

# Calculate
# Summation: "1 + 1" return 2
# Subtraction: "1 - 1" return 0
# Multiplication: "1 * 2" return 2
# Division: "5 / 2" return 2.5
# Percent: "5 % 10" return 5
# Range: "(1 + 2) = 10" return random between number 3 and 10

formula:
  money: "(%p_lvl% + {min}) = {max}"
  exp: "({min} * %p_lvl%) = {max}"

# Make sure you insert correct mob type
mob-list:
  Undead:
    EXP:
      Min: 1
      Max: 2
    Money:
      Min: 1
      Max: 2