# Modular options
# true = Disable module
# false = enable module
disable:
  money: false
  exp: false

# Internal Placeholder
# %p_lvl% -> return player level
# %m_lvl% -> return mob level
# PlaceholderAPi Support too

# Calculate
# Summation: "1 + 1" return 2
# Subtraction: "1 - 1" return 0
# Multiplication: "1 * 2" return 2
# Division: "5 / 2" return 2.5
# Percent: "5 % 10" return 5
# Range: "(1 + 2) = 10" return random between number 3 and 10

formula:
  money: "(%p_lvl% + %min%) = %max%"
  exp: "(%min% * %p_lvl%) = %max%"

# Make sure you insert correct mob type
mob-list:
  Undead:
    EXP:
      Min: 1
      Max: 2
    Money:
      Min: 1
      Max: 2